server {
    listen       80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    gzip on;
    gzip_min_length 1024;
    gzip_types text/html text/plain text/css application/javascript application/json image/svg+xml;

    # 不缓存，保证改动 index.html 后刷新页面即可生效
    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-store";
    }
}
